### ISSUE TITLE
Other code completion not working

### ISSUE THREAD

**Issue by maxrick** [Zignd/HTML-CSS-Class-Completion#1]
Other code completion like for snippets or for attributes inside a HTML-tag is not working. It only displays "Loading". If the extension is removed it works.

![htmlcodecompletion](https://cloud.githubusercontent.com/assets/12229737/13030574/43540404-d2b0-11e5-9f73-69be94c55e66.JPG)

**Comment by Zignd** [comment]
Thanks for letting me know, I will take a look into that right now.

**Comment by Zignd** [comment]
Fixed. A new version is already available at the Marketplace. Thanks again for this report @maxrick.
