### ISSUE TITLE
Error: command 'html-css-class-completion.cached' not found ???

### ISSUE THREAD

**Issue by KytoSai** [zignd/HTML-CSS-Class-Completion#109]
I updated to new version and have error. 
After i Ctrl+Shift+P and then typing "Cache CSS class definitions." Error display:
"command 'html-css-class-completion.cached' not found"

Demo:
http://prntscr.com/i0jmmf

**Comment by zignd** [comment]
Sorry, my mistake in the production build. Just released a new version that fixes the issue.

**Comment by KytoSai** [comment]
Thanks you ! It work fine !!! ^^

**Comment by ankuragrwl** [comment]
Not working on linux VS Code. I uninstalled and installed everything. Still not working

**Comment by davibusanello** [comment]
Same here problem here!
