### ISSUE TITLE
class completion stopped working

### ISSUE THREAD

**Issue by rwboyer** [zignd/HTML-CSS-Class-Completion#112]
Was working fine, stopped working as of a few days ago (possibly latest VS Code update Version 1.19.2 (1.19.2)).

No new plugins added.

**Comment by zignd** [comment]
That's weird because version 1.19.1 was broken due an issue in the dependencies, but I fixed the issue and released 1.19.2. What's your output in the developer console after clicking the lightning button (Help > Toggle Developer Tools)? Are there any errors?

**Comment by rwboyer** [comment]
@zignd 

sorry just saw this...

Here's the console output doesn't look like any issues related to this plugin.

<img width="912" alt="screen shot 2018-01-24 at 8 09 57 am" src="https://user-images.githubusercontent.com/85274/35333823-2b8ecd96-00de-11e8-9c99-2b763000cd1f.png">

**Comment by zignd** [comment]
No problem :)
