### ISSUE TITLE
Failed to cache the CSS classes in the workspace for the first time: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by OfficerHalf** [zignd/HTML-CSS-Class-Completion#114]
Insiders 1.20.0.
Intellisense for CSS class names 1.16.1
Windows 10

I get this error any time I open VS Code without a workspace. With a folder/workspace, things work as expected:
`Failed to cache the CSS classes in the workspace for the first time: Cannot read property 'map' of undefined`

I can click for another attempt, but just get the same error again.

**Comment by OfficerHalf** [comment]
![capture24](https://user-images.githubusercontent.com/4851889/35815266-b1f9247a-0a5d-11e8-9f8b-a735f5b3cdab.PNG)

**Comment by NoXPhasma** [comment]
I get the same error message since version 1.20.0 of VSCode.

**Comment by almadsen** [comment]
Get same on Mac, since VSCode 1.20.0

**Comment by lhq123456** [comment]
After updated to 1.20.0,I get this error too.

**Comment by jens1o** [comment]
Can reproduce this with an empty workspace.

**Comment by jkwuc89** [comment]
This happens every time I start Visual Studio Code 1.20.

**Comment by texjoachim** [comment]
Happens here in VSC 1.20.0 on openSUSE Tumbleweed, too.

**Comment by Almenon** [comment]
same issue


> /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:253 [Extension Host] VError: Failed to cache the CSS classes in the workspace for the first time: Cannot read property 'map' of undefined
	at C:\Users\Almenon\.vscode\extensions\Zignd.html-css-class-completion-1.16.1\out\src\extension.js:158:19
	at Generator.throw (<anonymous>)
	at rejected (C:\Users\Almenon\.vscode\extensions\Zignd.html-css-class-completion-1.16.1\out\src\extension.js:5:65)
	at <anonymous> (at C:\Users\Almenon\.vscode\extensions\Zignd.html-css-class-completion-1.16.1\out\src\extension.js:159:21)

**Comment by zignd** [comment]
There's a bug in the latest version of the API in which calling `vscode.workspace.findFiles` when the extension is not being executed inside a workspace, causes a "Cannot read property 'map' of undefined" error to be thrown from inside of it.

@Almenon I thought it was Bluebird initially, but it happened a few lines before this map call.

**Comment by jens1o** [comment]
@zignd I wonder why you cannot use activationEvents like
```json
 "activationEvents": [
    "onLanguage:css",
    "workspaceContains:**/*.css"
],
```

**Comment by zignd** [comment]
@jens1o That's actually a great idea. And there's no particular reason, I think the way it is right now is just what came to mind when I created the extension. I will keep that in mind!

**Comment by jens1o** [comment]
@zignd May I file a new issue for that?

**Comment by zignd** [comment]
@jens1o Yup, go ahead. Will help me not forget. Thanks XD
