### ISSUE TITLE
Not working with Vue files

### ISSUE THREAD

**Issue by alexbudure** [zignd/HTML-CSS-Class-Completion#117]
I have Vetur installed, yet it still doesn't seem to work. Any ideas?

**Comment by alexbudure** [comment]
Sorry, I should've been more clear. It recognizes styles in global css files, however it does not recognize the styles within the <style> tag in a Vue single file component.

**Comment by zignd** [comment]
No problem. Actually, the extension doesn't support CSS classes defined inside .vue files, it only supports auto-completion for the class attribute in this file format. You would have to define them on the outside.

**Comment by alexbudure** [comment]
Ohhh, is this something you're willing to consider? Coming from WebStorm, that was a pretty helpful feature.

**Comment by zignd** [comment]
Actually, that's something I never thought about, I didn't know Vue allowed you to do so (as I mostly use React in real life). But I will open another issue requesting this feature, so I can keep track of it.
