### ISSUE TITLE
at-rule or selector expected [error]

### ISSUE THREAD

**Issue by GranaT3** [zignd/HTML-CSS-Class-Completion#120]
visual studio code detects some errors, which have no meaning and did not appear before. How can I solve that? https://gist.github.com/GranaT3/c9a30c1f95815a8ab44800118640bb8f

![image](https://user-images.githubusercontent.com/17104324/36542793-41d74d4e-17b8-11e8-9d95-33bb65dede34.png)

**Comment by zignd** [comment]
Are you sure those errors are being generated by this extension? It shouldn't emit any errors at all.

Have you tried disabling it? Does the errors still appears?

**Comment by GranaT3** [comment]
puff, it seems that it was not the extension. I have disabled all the extensions and it follows the same. I do not know where to ask for help anymore.

Sorry.

**Comment by zignd** [comment]
No problem. But those are linter errors, they are usually configured to use certain rules by default. You should try something to fix those errors,
