### ISSUE TITLE
command 'html-css-class-completion.cache' not found

### ISSUE THREAD

**Issue by 7twin** [zignd/HTML-CSS-Class-Completion#121]
After updating to the newest vsCode 1.21.0-insider the plugin seems not to work anymore, even after fully wiping vsCode and the extension, it now only throws an error when I try to cache css:

`command 'html-css-class-completion.cache' not found`

**Comment by zignd** [comment]
Hi @7twin, that's very weird, I just tried the extension on VS Code 1.20.1 and on VS Code 1.21.0-insider, installed the extension on both and tried the automatic initial cache it performs, triggering the cache through the lightning icon and the "> Cache CSS class definition." All those use cases succeeded.

Which version of the extension are you on? The latest version is 1.17.1 from 02/18/2018.

**Comment by 7twin** [comment]
Hi @zignd I am on 1.17.1

**Comment by zignd** [comment]
Is there any log messages on your Developer Tools (Help > Toggle Developer Tools)? Especially error one. Would you mind posting them here?

Thanks!

**Comment by 7twin** [comment]
@zignd oh, it might have to do with me recently uninstalling node and something getting corrupted along the way? it can't find lodash:

`Activating extension 'Zignd.html-css-class-completion' failed: Cannot find module 'lodash'.`

Is there any way I could fix this, without reinstalling vscode etc. (including node) again?

**Comment by 7twin** [comment]
Reinstalling node, wiping all extensions from `%USERPROFILE%\.vscode-insiders\extensions` and reinstalling vsCode solved the issue.
