### ISSUE TITLE
Css completion only works when starting with a space

### ISSUE THREAD

**Issue by ericq86** [zignd/HTML-CSS-Class-Completion#122]
The auto completion does not work inside class="btn...". When typing class=" btn..." starting with a space it does work.
![2018-03-05_11-15-44](https://user-images.githubusercontent.com/25394596/36969782-cc11bd26-2066-11e8-8ac9-c71b90ea8c02.gif)

**Comment by johnw6761** [comment]
I also have this issue

**Comment by gezbo** [comment]
me too.

**Comment by Charlenze** [comment]
Same here, if you dont close the quotation marks you can write directly after ' class=" ' and get autocompletion

**Comment by Charlenze** [comment]
I saw there is already an issue on this #78

**Comment by gezbo** [comment]
Yes, I saw that after I posted. Ctrl+Space is a good workaround.
