### ISSUE TITLE
Hyphens in Class Names not handled appropriately

### ISSUE THREAD

**Issue by markadrake** [zignd/HTML-CSS-Class-Completion#13]
I can't test it right now because for some reason the extension is no longer pulling back class names at all - it shows the fetching notification and never ends.

However one thing I noticed is when I begin typing a class with a hyphen at the start, such as `-static`, that choosing to autocomplete it with your tool does not replace the first hyphen, so you end with `--static`.

It just doesn't choose to replace that hyphen character at the start.

**Comment by zignd** [comment]
Doesn't seem to be happening in the current version, it might have been fixed.
