### ISSUE TITLE
Extension don't work with VSCode 1.23.1

### ISSUE THREAD

**Issue by KytoSai** [zignd/HTML-CSS-Class-Completion#133]
Today, I updated my VSCode to versio 1.23.1. But "HTML-CSS-Class-Completion" extension don't work with VSCode 1.23.1.

When i use CTRL + SHIFT + P with command "Cache CSS class definitions."
Error: http://prntscr.com/jgl1wi

Sorry, I'm not good english !

**Comment by zignd** [comment]
It happened with me as well, the build failed and I ended up publishing the extension like that by mistake. The latest version should be ok. Sorry for taking this long to reply.
