### ISSUE TITLE
The extension don't work and the lightning icon don't appear

### ISSUE THREAD

**Issue by Beta6484** [zignd/HTML-CSS-Class-Completion#134]
Hello, I use vscode with this extension at home and in the office, I use the same extensions in both cases, the settings are synchronized. Unfortunately at home the plugin does not work, I already uninstalled and reinstalled. The lightning icon does not even appear. I know they use git for spot errors, but I have not found another channel on which I could get help. Thanks.

**Comment by zignd** [comment]
Hi @Beta6484, usually the icon won't show up when the extension can't find parsable files in the workspace, which would include, CSS, HTML, PHP files, and the other supported file formats. Did I help you some how? There's also another point which you can check, go to the Help > Toggle Developer Tools menu option, then click the Console tab and check for errors related to this extension.

**Comment by Beta6484** [comment]
Hi good night!
No error found. I even tried to change the "html-css-class-completion.includeGlobPattern" setting to the path of the css files and it still does not work. The worst that in the office the extension work with a more complex project in webforms! At home the project is simpler just with scss, css, htm and js files and it doesn't work :'(

**Comment by zignd** [comment]
Sorry for taking this long to reply @Beta6484, have you managed to get the extension to function correctly?
