### ISSUE TITLE
Add support for OctoberCMS templates

### ISSUE THREAD

**Issue by martin-badin** [zignd/HTML-CSS-Class-Completion#137]
Hello,

please add support for OctoberCMS templates if possible. As a template language is used Twig.
Here is an example of how the css file is attached.

```twig
<link rel="stylesheet" type="text/css" href="{{ 'assets/css/style.min.css' | theme }}">
```

**Comment by muuvmuuv** [comment]
You can add other extensions by adding this to your VSCode settings: `"html-css-class-completion.includeGlobPattern": "**/*.{css,html,scss}",`
