### ISSUE TITLE
not support scss

### ISSUE THREAD

**Issue by ZSkycat** [zignd/HTML-CSS-Class-Completion#142]
output in console
```
[Extension Host]% 5 failed attempts to parse. List of the documents:
[Extension Host] /d:/WorkspaceSync/vue-typescript-solution/src/style/base.scss
/d:/WorkspaceSync/vue-typescript-solution/src/style/help.scss
/d:/WorkspaceSync/vue-typescript-solution/src/style/var.scss
/d:/WorkspaceSync/vue-typescript-solution/src/style/app-vueclass/index.scss
/d:/WorkspaceSync/vue-typescript-solution/src/style/app-vueclass/component/ViewColor.scss
```

**Comment by muuvmuuv** [comment]
What about: `"html-css-class-completion.includeGlobPattern": "**/*.{css,html,scss}",`

**Comment by mkbctrl** [comment]
@muuvmuuv smth is wrong here, I try to add the following snippet:
`"html-css-class-completion.includeGlobPattern" : "app/assets/*.{scss,html}"`
or 
`"html-css-class-completion.includeGlobPattern" : "app/assets/*.{css,scss,html}"`

and after 1st reload nothing chaged, intelli sense didn't found new classnames,
after 2nd and more reloads the `lightning icon` just disappeared and stoped working at all

**Comment by muuvmuuv** [comment]
Try to include the double-star before the app selector or try the global glob. Normally this should work (it works on my system with scss)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ixrock** [comment]
Sad but true, class names from `.sass`/`*.scss` files not working ..
(with `"html-css-class-completion.includeGlobPattern": "**/*.{css,html,scss}"`)

And it seems it's not officially supported for now:
> Gives you autocompletion for CSS class definitions that can be found in your workspace (defined in CSS files or the in the file types listed in the Supported Language Modes section)

And there is no SASS/SCSS listed in this section..
https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion

Please add SASS support and thanks for the extension! 🙏

**Comment by zignd** [comment]
Currently there's no support for Sass, but there's already an open issue to track this at #10.
