### ISSUE TITLE
Wont suggest css classes unless you first make a space.

### ISSUE THREAD

**Issue by GabMic** [zignd/HTML-CSS-Class-Completion#147]
This is very strange.
In this case: `<div class="myClass"></div>` it wont work.
But in this case: `<div class=" myClass"></div>` it does work.

Notice the space before the class name in the second line.
What can be the problem?

**Comment by myfonj** [comment]
I assume you are supposed to invoke suggestions with <kbd>ctrl</kbd><kbd>space</kbd> in this case (?)

**Comment by zignd** [comment]
This is the intended behavior. As @myfonj said you have to press <kbd>CTRL</kbd>+<kbd>Space</kbd> in order to trigger the suggestions. It's just how I thought it would make sense at the time I developed it, you can suggest a different behavior opening a new issue.
