### ISSUE TITLE
[FR] accept array for option "excludeGlobPattern"

### ISSUE THREAD

**Issue by jimblue** [zignd/HTML-CSS-Class-Completion#153]
Hi,

Actually excludeGlobPattern only accept string so it's impossible to exclude multiple folder.
This cost a huge drop in performance when working with a CMS with a tone of CSS class for the backend that are obviously not needed for auto completion.

Best

**Comment by KamasamaK** [comment]
You should be able to define multiple alternative folders using something like `{foo,bar}`.
