### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by fnouama** [zignd/HTML-CSS-Class-Completion#156]
- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.18.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/franck/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zignd** [comment]
There's already an open issue regarding high CPU usage. https://github.com/zignd/HTML-CSS-Class-Completion/issues/155
