### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MilesMaillu** [zignd/HTML-CSS-Class-Completion#175]
- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.18.0`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.32.3`

[Zignd.html-css-class-completion-unresponsive.cpuprofile.txt](https://github.com/zignd/HTML-CSS-Class-Completion/files/2980690/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by MilesMaillu** [comment]
[Zignd.html-css-class-completion-unresponsive.cpuprofile.txt](https://github.com/zignd/HTML-CSS-Class-Completion/files/2980690/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt)

**Comment by zignd** [comment]
Centralizing the discussion on issue #155.
