### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by staceyb** [zignd/HTML-CSS-Class-Completion#180]
[-](url
[Zignd.html-css-class-completion-unresponsive.cpuprofile.txt](https://github.com/zignd/HTML-CSS-Class-Completion/files/3005706/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt)
) Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.18.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/stacey/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zignd** [comment]
Thanks for attaching the file. I'll be closing the issue and mentioning it on #155. Just so we can centralize the discussion there.
