### ISSUE TITLE
html css class completion  plugin bug, vs code not work, only close

### ISSUE THREAD

**Issue by joaomoreno** [Zignd/HTML-CSS-Class-Completion#19]
_From @blusoul on July 8, 2016 7:8_

- VSCode Version: 1.3 
- OS Version: windows 10

Steps to Reproduce:

1. vs Code 
2. tips  html css class completion; Fetching css rules from css files please wait 
![image](https://cloud.githubusercontent.com/assets/8167270/16680554/f10d7f92-4521-11e6-96e7-5b5e44875569.png)

_Copied from original issue: Microsoft/vscode#8904_

**Comment by Zignd** [comment]
Fixed on the latest release. Thanks!
