### ISSUE TITLE
Does not work with Svelte files

### ISSUE THREAD

**Issue by Narungsih** [zignd/HTML-CSS-Class-Completion#200]
css class completion version 1.18
vscode version 1.33.1

"css.remoteStyleSheets" : ["https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"] it's doesn't work with Svelte files

**Comment by zignd** [comment]
Hi there @Narungsih, would mind giving me a short explanation of what is "Svelte files"? Is it some sort of CSS framework you would like the extension to support? The only thing I could find is this project named [svelte](http://sveltejs.com/). Also, this "css.remoteStyleSheets" setting is not supported in this extension. Currently, it gets those URLs from HTML link tags and retrieves the CSS file they refer to.

**Comment by skdigital** [comment]
Hi,

Svelte is a new frontend javascript framework that is developing nicely, it just hit version 3. Its actually a javascript compiler that can ship a full webapps code as small as preact (around 3kb) after compilation. There is also a nice framework built around svelte called Sapper that is very similar to reacts Nextjs. Svelts's Sapper runs much faster and smaller than Next.js, and has a few very interesting nice to have features that make developing with it very nice. 

Trust me, Svelte and Sapper are going to do very well. It's basically the birth child between Vuejs and Reacts with much better speed and bundle sizes.

Hope this helps.

Here are the links to the respective framework pages.
Svelte: https://svelte.dev
Sapper: https://sapper.svelte.dev/

Bests,

SK
