### ISSUE TITLE
Extension doesn't respond on VS Code launch in macOS

### ISSUE THREAD

**Issue by brianhoch** [zignd/HTML-CSS-Class-Completion#207]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.34.0`

[Zignd.html-css-class-completion-unresponsive.cpuprofile.txt](https://github.com/zignd/HTML-CSS-Class-Completion/files/3219053/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt)

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 7846,
		"activateCallTime": 3,
		"activateResolvedTime": 22,
		"activationEvent": "*"
	},
	"runtimeErrors": []
}
```

**Comment by zignd** [comment]
Thanks for attaching the file. I'll be closing the issue and mentioning it on #155. Just so we can centralize the discussion there.
