### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by wanderer6994** [zignd/HTML-CSS-Class-Completion#213]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Windows_NT x64 10.0.18898`
- VSCode version: `1.35.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by wanderer6994** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 131071,
		"activateCallTime": 4,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	},
	"runtimeErrors": []
}
```

**Comment by zignd** [comment]
Thanks for the report. I'll be closing the issue and mentioning it on #155. Just so we can centralize the discussion there.
