### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Darasimi-Ajewole** [zignd/HTML-CSS-Class-Completion#214]
[Zignd.html-css-class-completion-unresponsive.cpuprofile.txt](https://github.com/zignd/HTML-CSS-Class-Completion/files/3358515/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Linux ia32 4.15.0-52-generic`
- VSCode version: `1.33.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zignd** [comment]
Thanks for attaching the file. I'll be closing the issue and mentioning it on #155. Just so we can centralize the discussion there.
