### ISSUE TITLE
CSS Class Completion Extension locks up whole of VS Code v1.3 or v1.3.1

### ISSUE THREAD

**Issue by Howshall** [Zignd/HTML-CSS-Class-Completion#22]
Previously been using this extension successfully with previous versions of Visual Studio Code on Windows, but now as of v1.3 (and still with new latest v1.3.1) the CSS extension comes up with initial 'Fetching CSS rules...' message but then whole VS Code editor window hangs.

VS Code becomes entirely unresponsive with no ability to scroll or move text cursor within source code, or to click on any VS Code application left side icons or files in Explorer view tree. Only top File, Edit, View menu item options are still responsive.

Currently having to uninstall this extention until this issue is fixed. Others also having this problem as shown by new 1 star reviews being submitted at https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion bottom User Reviews section.

**Comment by Liero** [comment]
Fix this, please!

**Comment by Zignd** [comment]
Fixed on the latest release. Thanks for the feedback!

**Comment by Howshall** [comment]
Confirm this issues appears fixed for me on re-test with same HTML project under current latest VS Code 1.5.1
Thanks!

**Comment by Zignd** [comment]
Thanks for the confirmation @Howshall!
