### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by graphicom** [zignd/HTML-CSS-Class-Completion#224]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.38.0`
Performance issue, the extenssion takes a long time to complete its task and prevent others from runing.

**Comment by zignd** [comment]
Already reported here: https://github.com/zignd/HTML-CSS-Class-Completion/issues/155
