### ISSUE TITLE
command 'html-css-class-completion.cache' already exists

### ISSUE THREAD

**Issue by roojay520** [zignd/HTML-CSS-Class-Completion#228]
VSCode Version: 1.39.1
OS Version: OSX 10.14.6
Extension Version: 1.18

Desc: Activating extension `Zignd.html-css-class-completion` failed:  command 'html-css-class-completion.cache' already exists

![image](https://user-images.githubusercontent.com/11495164/66825596-24459080-ef7d-11e9-97f8-0405617d4938.png)

**Comment by zignd** [comment]
I believe we fixed this issue, would you mind trying it again?
