### ISSUE TITLE
html-css-class-completion.cache not found

### ISSUE THREAD

**Issue by richardgnz1** [zignd/HTML-CSS-Class-Completion#229]
<h1>html-css-class-completion.cache</h1>
<h2>not found</h2>
<p><b>Visual Stuido Code Version: 1.39.2</b></p>
<p><b>Platform: Windows 10</b></p>
<a href="https://microtec2017.com/github/media/css-error.jpg" target="_blank" rel="noopener noreferrer">Imagen</a>

**Comment by zignd** [comment]
I believe we fixed this issue. Please try it again
