### ISSUE TITLE
css class autocomplete

### ISSUE THREAD

**Issue by Highter87** [zignd/HTML-CSS-Class-Completion#230]
Hello!
Don't work css class autocomplete for *.svelte files.

![image](https://user-images.githubusercontent.com/17083227/68383197-3e325780-0166-11ea-9c81-93c3acc680a7.png)

It is new javascript framework. You can see: https://svelte.dev/
in short - this is an analogue of Vue.js cli
Vue.js has a * .vue file extension, and Svelte has - * .svelte

**Comment by Zenthae** [comment]
you can manually add support by going into you're extension folder  zignd.html-css-class-completion-1.19.0/out/src/extension.js 

```js
   // HTML based extensions
    [
      'html',
      'django-html',
      'razor',
      'php',
      'blade',
      'vue',
      'twig',
      'markdown',
      'erb',
      'handlebars',
      'ejs',
      'svelte', // <== add this
    ].forEach((extension) => {
      context.subscriptions.push(provideCompletionItemsGenerator(extension, /class=["|']([\w- ]*$)/));
    });
```

**Comment by zignd** [comment]
You can now do that without hacks from the user settings as described in this section in the README.md https://github.com/zignd/HTML-CSS-Class-Completion#extended-support-for-other-language-modes
