### ISSUE TITLE
Disable completion by file extension

### ISSUE THREAD

**Issue by guillenotfound** [zignd/HTML-CSS-Class-Completion#232]
It would be really useful to disable class completion by file extension, having useless suggestions doesn't help at all...

This is a test:
![image](https://user-images.githubusercontent.com/5492960/71646169-d4f13f80-2ce3-11ea-83e1-7b34bbf76614.png)

And I'm getting all tailwind suggestion, I now I can disable with:

```
"[javascript]": {
    "editor.suggest.showVariables": false
  },
```

But it I won't be able to get variables that in fact I use...

**Comment by IslombekMe** [comment]
I'm having this issue too. I'd love it to be fixed; it freaks me out sometimes.

**Comment by zignd** [comment]
I believe you can use this feature that allows you to ignore files matching a pattern: https://github.com/zignd/HTML-CSS-Class-Completion#folders-and-files
