### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by shivling1254** [zignd/HTML-CSS-Class-Completion#238]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.43.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by zignd** [comment]
Already reported here: https://github.com/zignd/HTML-CSS-Class-Completion/issues/155
