### ISSUE TITLE
Does not work with php files

### ISSUE THREAD

**Issue by Sarkanyolo** [zignd/HTML-CSS-Class-Completion#24]
This plugin is great, but it only triggers on html files.
Please, make it work with php files also!

**Comment by Zignd** [comment]
I will work on that as soon as I finish the support for `<link>` elements and `<style>` elements. :blush:

**Comment by AurelioDeRosa** [comment]
Handlebars (and all other template languages really) should be supported as well.

**Comment by zignd** [comment]
Closing this issue as the latest version now has support for PHP. And I'm gonna move the Handlebars request into its own issue.
