### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by endrixh7** [zignd/HTML-CSS-Class-Completion#243]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Linux x64 5.4.0-28-generic`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by zignd** [comment]
Already reported here: https://github.com/zignd/HTML-CSS-Class-Completion/issues/155
