### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by jsahil730** [zignd/HTML-CSS-Class-Completion#246]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Linux x64 4.15.0-99-generic`
- VSCode version: `1.45.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 11143,
		"activateCallTime": 2,
		"activateResolvedTime": 42,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "Zignd.html-css-class-completion",
				"_lower": "zignd.html-css-class-completion"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by zignd** [comment]
Already reported here: https://github.com/zignd/HTML-CSS-Class-Completion/issues/155
