### ISSUE TITLE
FR: config for languageModes

### ISSUE THREAD

**Issue by Mordef** [zignd/HTML-CSS-Class-Completion#249]
Atm there is:
```ts
    const languageModes = ["html", "django-html", "razor", "php", "blade", "vue", "twig", "markdown", "erb",
        "handlebars", "ejs", "typescriptreact", "javascript", "javascriptreact"];
```
Can u export this to setting, so we can add more languages?
I have added "smarty" directly and work fine.

**Comment by zignd** [comment]
@Mordef we added this very specific feature, check this section of the READM.md for more details https://github.com/zignd/HTML-CSS-Class-Completion#extended-support-for-other-language-modes
