### ISSUE TITLE
Add support for CSS styles specified inline within STYLE in HTML page source

### ISSUE THREAD

**Issue by Howshall** [zignd/HTML-CSS-Class-Completion#25]
Given having CSS specified in external linked CSS file is best practice, this request is likely low priority enhancement unless others also need/vote for this?

However for some of my projects which are particularly 1st load performance focused I do have instances of projects where the majority of a page's CSS styles are specified directly in the HTML source within a STYLE tag in the HEAD of the page. (To avoid extra HTTP requests of externally linked files)

If this feature was added to the extension I'd guess it would be good to review and cache the contents of all <style type="text/css"> within the HTML document source?

**Comment by Zignd** [comment]
It is indeed a necessary feature, I will work on the support for CSS class definitions from `<link>` elements and `<style>` elements this weekend or maybe even sooner depending on my demands at work. Thanks for the feedback! :grin:

**Comment by zignd** [comment]
Closing this issue as the latest version now has support for CSS class defined in `style` tags and also those referenced through `link` tags.
