### ISSUE TITLE
How to reference to external scss file

### ISSUE THREAD

**Issue by TomThak** [zignd/HTML-CSS-Class-Completion#250]
Hello,
i am quite noob in visual studio. 
I would like to ask - if I have for example php website,
which constists of for example header, body, footer and my css file is linked in header
and I open for example body, i have no autocomplete suggestions due to no linked stylesheed in the body.php file. How can I refer to the css / sass file included in header? 
It is common thing, that project is split into several files on server, but there is not css file linked in every single file of the page. 

Thanks for help!

**Comment by zignd** [comment]
Are you opening your file individually on Visual Studio Code, or are you using a workspace (when you open a folder in VS Code)? I believe it should work even in this scenario when you're using workspaces.
