### ISSUE TITLE
Extension issue 

### ISSUE THREAD

**Issue by SulthanNK** [zignd/HTML-CSS-Class-Completion#251]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.46.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 6919,
		"activateCallTime": 4,
		"activateResolvedTime": 713,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "Zignd.html-css-class-completion",
				"_lower": "zignd.html-css-class-completion"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by zignd** [comment]
Already reported here: https://github.com/zignd/HTML-CSS-Class-Completion/issues/155
