### ISSUE TITLE
Could you make it support hoverClass in .tsx?

### ISSUE THREAD

**Issue by ado5** [zignd/HTML-CSS-Class-Completion#257]
In react，

```
      <Button className="bg-blue-500 text-white font-bold py-2 px-4" hoverClass="bg-blue-700">
        Button
      </Button>
```

Thank you!

**Comment by zignd** [comment]
I didn't know about this hoverClass, is it a custom attribute interpreted by a library other than React? Do you mind providing me with a link to a documentation on this attribute?
