### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by WayneLambert** [zignd/HTML-CSS-Class-Completion#258]
Hi,

This extension has become unresponsive and basically ground VS Code to a halt. I'm sure the extension users would be grateful if you would please look into it.

Here are the settings generated from the command palette using: `Developer: Show Running Extensions`

- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.47.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 508,
		"activateCallTime": 4,
		"activateResolvedTime": 31095,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "Zignd.html-css-class-completion",
				"_lower": "zignd.html-css-class-completion"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

Thank you!

**Comment by zignd** [comment]
Already reported here: https://github.com/zignd/HTML-CSS-Class-Completion/issues/155
