### ISSUE TITLE
Failing to recommend right class

### ISSUE THREAD

**Issue by pavangayakwad** [zignd/HTML-CSS-Class-Completion#260]
The extension is really missing the point, please find the screenshot, it is failing to make right recommendation over intellisense. Am I missing something here? Would be great if it is fixed. Thanks.

![image](https://user-images.githubusercontent.com/1834890/90169763-acbed880-ddbc-11ea-91f5-1cc4915f4743.png)

**Comment by pavangayakwad** [comment]
..and it worked fine after installing the HTML CSS support plugin, is this a prerequisite?

![image](https://user-images.githubusercontent.com/1834890/90170119-2951b700-ddbd-11ea-870d-ace1e7d009ce.png)

**Comment by zignd** [comment]
Woah, that's really weird, that's one example of usage I always attempt to do by myself when using Bootstrap for example and it always work. I wonder if it could be conflicting extensions.
