### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by p-arab** [zignd/HTML-CSS-Class-Completion#263]
- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Linux x64 4.20.11-100.fc28.x86_64`
- VSCode version: `1.32.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/parab/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zignd** [comment]
Already reported here: https://github.com/zignd/HTML-CSS-Class-Completion/issues/155
