### ISSUE TITLE
Version of this plugin in reverse

### ISSUE THREAD

**Issue by studio-blueboat** [zignd/HTML-CSS-Class-Completion#265]
Hi there,

Just wondering if there is a version of this plugin that operates in reverse, i.e. looks at class names in html files and makes the available for definition in css, less and sass files.

**Comment by jorgegarba** [comment]
I think is not an issue

**Comment by zignd** [comment]
It could be implemented, but I believe it would diverge from the context this extension tries to tackle. Maybe it would be more fitted for a whole new extension and one that already exists and focus specifically on css, less or sass.
