### ISSUE TITLE
Please deprecate this plugin

### ISSUE THREAD

**Issue by avarayr** [zignd/HTML-CSS-Class-Completion#268]
# ⚠️  PLEASE DEPRECATE THIS PLUGIN IF NO LONGER MAINTAINED! ⚠️ 

- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Darwin x64 20.1.0`
- VSCode version: `1.49.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 602,
		"activateCallTime": 57,
		"activateResolvedTime": 12867,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "Zignd.html-css-class-completion",
				"_lower": "zignd.html-css-class-completion"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by zignd** [comment]
Already reported here: https://github.com/zignd/HTML-CSS-Class-Completion/issues/155
