### ISSUE TITLE
Add option to ignore a folder

### ISSUE THREAD

**Issue by tf2manu994** [zignd/HTML-CSS-Class-Completion#27]
For instance, I have a folder (node_modules), where most of the folders in there aren't relevant.

It would be awesome if we had gitignore-type ignoring, so I could do something like this:

```
node_modules/**
!node_modules/material-design-lite/material.*
```

**Comment by aedryan** [comment]
+1

**Comment by york-xtrem** [comment]
Or the option to choose folder.

Thanks

**Comment by rnemec** [comment]
Is this extension actively developed / maintained?

**Comment by zignd** [comment]
The recently released version adds a feature that is supposed to solve this issue.
