### ISSUE TITLE
Extension issue```json  { 	"messages": [], 	"activationTimes": { 		"codeLoadingTime": 8784, 		"activateCallTime": 2, 		"activateResolvedTime": 31, 		"activationReason": { 			"startup": true, 			"extensionId": { 				"value": "Zignd.html-css-class-completion", 				"_lower": "zignd.html-css-class-completion" 			}, 			"activationEvent": "*" 		} 	}, 	"runtimeErrors": [] } ```

### ISSUE THREAD

**Issue by PriyankeshRaj** [zignd/HTML-CSS-Class-Completion#274]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by zignd** [comment]
Already reported here: https://github.com/zignd/HTML-CSS-Class-Completion/issues/155
