### ISSUE TITLE
Stopped working after vs code update to 1.6

### ISSUE THREAD

**Issue by felixpis** [Zignd/HTML-CSS-Class-Completion#28]
Today I've updated visual studio code to 1.6 version and css completion stopped working

**Comment by Learn-Digital-Audio** [comment]
It's happening in PathIntellisense too, could be related https://github.com/ChristianKohler/PathIntellisense/issues/30

**Comment by Howshall** [comment]
Agree and confirm Zignd's plugin has stopped working for me too under VS Code 1.6. 

I do normally still get status bar update saying that all styles have been cached, but then no actual CSS classes offer auto-complete in same project that things were working fine in under VSCode 1.5.

Note 10-20% of time on opening my largest/most complicated project Zignd's plugin seems to cause VSCode 1.6 to lockup (as I've had no lockups when Zignd's plugin uninstalled) which also suggests something has changed VSCode 1.5 to 1.6?

**Comment by thwbn** [comment]
+1
worked fine on a normal machine, even in VS Code 1.6.1. But it kills the vscode PORTABLE version. It is freezes the screen with no chance of closing the file or changing the folder.
VS Code was only closeable in the task manager.

Th

**Comment by Howshall** [comment]
Confirm Zignd's plugin started re-working with my standard install VS Code 1.6.1, so appears there was a plugin breaking problem with just VS Code 1.6.0

**Comment by eappell** [comment]
I'm running VS Code 1.6.1 and if I run with this extension it crashes my VS Code on startup.  The only way I can start VS Code without locking up is to remove this extension.  I have 24 other extensions, and this was the only that caused that issue.

**Comment by Howshall** [comment]
@eappell As I only run 2-3 plugins and to assist @Zignd debug your problem can you confirm that you still have problems with Zignd's CSS extension if you remove (or at least disable) all other plugins in your VS Code 1.6.1 except for Zignd's CSS one? Do you still get problems in that case?

IF you can run it solo, can you then start re-enabling other extensions until you find if it's just a cumulative number, or a specific other plugin that might be interacting?

**Comment by sgoodgrove** [comment]
I am suffering with the same issue as @eappell
With VSCode 1.6.1 and **Zignd.html-css-class-completion-1.0.3** in my extensions folder VSCode will load and initially work, but it will freeze the text editor pane after a couple of seconds. The menus are still clickable but are either unresponsive or barely responsive.

With the folder **Zignd.html-css-class-completion-1.0.3** removed everything springs back into life.

**Comment by thwbn** [comment]
01.11.16:
after deleting the plug in and running vs code 1.6.1 without it - everything were fine. And accedentelly I reinstalled the CSS Class Completion plug in again (straight from VS Code n ot manually)- and it works now??!! Well, at least it seems to work, and VS Code too.

**Comment by sgoodgrove** [comment]
Update from me. It **may** be linked to when my explorer is set to certain folders i.e. a folder with a particularly large source code repository.

**Comment by rich25200** [comment]
Same issue for me! I need delete the extension otherwise VS code is not working.
