### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by QueztionMark** [zignd/HTML-CSS-Class-Completion#280]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Windows_NT ia32 10.0.18363`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by zignd** [comment]
Already reported here: https://github.com/zignd/HTML-CSS-Class-Completion/issues/155
