### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by dmGusai15** [zignd/HTML-CSS-Class-Completion#284]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.52.0`

Could not read source map for file:///c:/..../.vscode/extensions/zignd.html-css-class-completion-1.19.0/node_modules/performance-now/lib/performance-now.js: ENOENT: no such file or directory, open 'c:\...\.vscode\extensions\zignd.html-css-class-completion-1.19.0\node_modules\performance-now\lib\performance-now.js.map'

Could not read source map for file:///d:/Microsoft%20VS%20Code/resources/app/extensions/ms-vscode.node-debug2/out/src/extension.js: ENOENT: no such file or directory, open 'd:\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\extension.js.map'

**Comment by zignd** [comment]
Already reported here: https://github.com/zignd/HTML-CSS-Class-Completion/issues/155
