### ISSUE TITLE
Manually refetch command

### ISSUE THREAD

**Issue by piotrwitek** [Zignd/HTML-CSS-Class-Completion#3]
Hi,
Please could you add a command to manually refetch css for opened html, when adding new classes they are not propagated so the only workaroung is to restart the editor.

**Comment by Zignd** [comment]
I'll add that.

**Comment by Angelinsky7** [comment]
I've permitted my-self to simply add this into the extension at line 141
```
var disposable = vscode.commands.registerCommand('extension.html-css-class-completion.refresh', () => {
        fetchAllCssRulesInCssFiles();
    });
    context.subscriptions.push(disposable);
```

**Comment by Zignd** [comment]
Added this feature on the latest release that's already on the Marketplace. Thanks for the feedback! (On the extension page there are some GIFs demonstrating how to use it https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion)
