### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by zbynio4** [zignd/HTML-CSS-Class-Completion#301]
- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.19.0`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/zbynio/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zignd** [comment]
Already reported here: https://github.com/zignd/HTML-CSS-Class-Completion/issues/155
