### ISSUE TITLE
extension issue 

### ISSUE THREAD

**Issue by yanai101** [zignd/HTML-CSS-Class-Completion#305]
I got in the development console this error:

`<number> failed attempts to parse. List of the documents: <list of files>`

maybe do you have a parser issue?

the list is a most HTML files, but there are some CSS files

**Comment by zignd** [comment]
Sometimes the parser fails to parse the CSS files it found, due to unsupported features and maybe syntax related to custom CSS preprocessors like Sass or Less. Could you provide a sample of the CSS file it failed to parse? In case it's an open-source code or something you are allowed to share.
