### ISSUE TITLE
45588

### ISSUE THREAD

**Issue by a0989652492** [zignd/HTML-CSS-Class-Completion#311]
Issue Type: <b>Bug</b>

777

Extension version: 1.20.0
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU        P6200  @ 2.13GHz (2 x 2128)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|1.92GB (0.24GB free)|
|Process Argv|C:" --crash-reporter-id 14add16d-5893-4410-96c7-fe8a12e99e22|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30265425
wslfolderdoccf:30282075
vsget980:30279783
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953

```

</details>

**Comment by zignd** [comment]
Seems to be already reported at #155
