### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by olasoj** [zignd/HTML-CSS-Class-Completion#312]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.20.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 222,
		"activateCallTime": 3,
		"activateResolvedTime": 46421,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "Zignd.html-css-class-completion",
				"_lower": "zignd.html-css-class-completion"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by zignd** [comment]
Seems to be already reported at #155
