### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mehrzadtajkarimi** [zignd/HTML-CSS-Class-Completion#316]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.20.0`
- OS Version: `Linux x64 5.8.0-48-generic`
- VS Code version: `1.55.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by zignd** [comment]
Seems to be already reported at #155
