### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by PCOffline** [zignd/HTML-CSS-Class-Completion#319]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.20.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VS Code version: `1.55.2`

```JSON 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 15455,
		"activateCallTime": 1,
		"activateResolvedTime": 672,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "wix.vscode-import-cost",
				"_lower": "wix.vscode-import-cost"
			},
			"activationEvent": "onLanguage:javascript"
		}
	},
	"runtimeErrors": []
}
```

**Comment by zignd** [comment]
I need more information on what actually happened, something like the console output. Did errors show up there?

**Comment by PCOffline** [comment]
This happened over 2 months ago, even if I would remember what happened, I can't give you any console output.
