### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by PCOffline** [zignd/HTML-CSS-Class-Completion#320]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.20.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VS Code version: `1.55.2`

```JSON 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 177,
		"activateCallTime": 2,
		"activateResolvedTime": 116240,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "Zignd.html-css-class-completion",
				"_lower": "zignd.html-css-class-completion"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by zignd** [comment]
I need more information on what actually happened, something like the console output. Did errors show up there?
