### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by TadasBalsys** [zignd/HTML-CSS-Class-Completion#325]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.20.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 230,
		"activateCallTime": 2,
		"activateResolvedTime": 212852,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "Zignd.html-css-class-completion",
				"_lower": "zignd.html-css-class-completion"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by zignd** [comment]
I need more information on what actually happened, something like the console output. Did errors show up there?
