### ISSUE TITLE
REPORT BUG TEST VAISON

### ISSUE THREAD

**Issue by pts311** [zignd/HTML-CSS-Class-Completion#331]
Issue Type: <b>Bug</b>

THIS IS A TEST.

Extension version: 1.20.0
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 15.6.0

**Comment by zignd** [comment]
I need more information on what actually happened, something like the console output. Did errors show up there?
