### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by 0xS4N4TG** [zignd/HTML-CSS-Class-Completion#333]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.20.0`
- OS Version: `Linux x64 5.4.0-73-generic`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by zignd** [comment]
Please provide more information.
