### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by virendrasingh02** [zignd/HTML-CSS-Class-Completion#337]

**Comment by AbdulRafaySalsoftNew** [comment]
issue
[Zignd.html-css-class-completion-unresponsive.cpuprofile.txt](https://github.com/zignd/HTML-CSS-Class-Completion/files/6717546/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt)

**Comment by zignd** [comment]
Thanks for attaching the file. I'll be closing the issue and it will be mentioned on #155. Just so we can centralize the discussion there.
