### ISSUE TITLE
Save file slowdown and intellisense not working

### ISSUE THREAD

**Issue by discomarra** [zignd/HTML-CSS-Class-Completion#35]
I experienced a slowdown when saving js files and also the intellisense is not working while this extension is enabled. 
More info https://github.com/Microsoft/vscode/issues/15105

**Comment by arnaudauroux** [comment]
I have the same issue here, no intellisense and a big slowdown.
Version: 1.0.3
VS Code Version: 1.8.1

**Comment by noilly** [comment]
I also have this issue. I have experienced the above-mentioned issues, and also the preview pane for Markdown stops working.

Only fix is to disable the extension.

**Comment by jacobedawson** [comment]
I've experienced the same problem recently, only disabling the extension has fixed the issue, unfortunately.

**Comment by zignd** [comment]
I guess this issue has been fixed in the latest update. Thanks to Erich Gamma for this great pull request #90.
