### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rock-yas** [zignd/HTML-CSS-Class-Completion#352]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.20.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VS Code version: `1.60.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by zignd** [comment]
Seems to be already reported at #155
