### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by XTechnology-TR** [zignd/HTML-CSS-Class-Completion#359]
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.20.0`
- OS Version: `Linux x64 5.14.2-1-MANJARO`
- VS Code version: `1.60.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by zignd** [comment]
Seems to be already reported at #155
