### ISSUE TITLE
Support for React

### ISSUE THREAD

**Issue by achtan** [Zignd/HTML-CSS-Class-Completion#36]
pls add support for React `className`

**Comment by gnhuy91** [comment]
+1 would be awesome

**Comment by Jacobfred88** [comment]
+1

**Comment by JanneHarju** [comment]
+1

can someone else make this if author is occupied.

**Comment by JanneHarju** [comment]
I just wrote support for javascript (.js -files) and for react typescript files (.tsx) but I think that I don't have permission to push new branch to repository.

**Comment by Zignd** [comment]
Hi @JanneHarju, I'm the repository owner, you can create a pull request with your changes, I'd be glad to accept it. In case you're not familiar with the concept of pull requests, GitHub has some documents explaining how you would go in order to create one.

**Comment by JanneHarju** [comment]
@Zignd  I try to make pull request with source tree put 403 error occur. I make own branch for my changes. When I make pull request it says that it try to push those changes at same time.

**Comment by Zignd** [comment]
@JanneHarju Consider using the GitHub website to create the pull request, it's easier for that. Remember that you need to fork the project, then you make the changes to the forked repository and after that, you make a pull request to merge the forked repository into this repository.

**Comment by JanneHarju** [comment]
Yes I make branch and trying to push that but I don't have permission to make branch I think. Here is what sourde tree says.
git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags --set-upstream origin Support_for_react:master
Pushing to ssh://git@github.com/Zignd/HTML-CSS-Class-Completion.git
ERROR: Permission to Zignd/HTML-CSS-Class-Completion.git denied to JanneHarju.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Zignd** [comment]
@JanneHarju  You can't push a change directly to this repository. You need
to push it to your forked repository and create a pull request from the
GitHub website.

**Comment by JanneHarju** [comment]
OK now I managed to fork it and make pull request. How soon you think you can merge and publish it to market?

**Comment by JanneHarju** [comment]
Now I have problem with debugginf extension. debugging Visual studio appears and soon just shutdown. Do you have same problem?

**Comment by Zignd** [comment]
> OK now I managed to fork it and make pull request. How soon you think you can merge and publish it to market?

@JanneHarju Great, I'm going to start reviewing it right now and if everything goes fine I will be publishing it to the market today.

> Now I have problem with debugginf extension. debugging Visual studio appears and soon just shutdown. Do you have same problem?

@JanneHarju It usually works for me, that's weird.

**Comment by Zignd** [comment]
Feature added in the [latest version](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion) thanks to @JanneHarju.
