### ISSUE TITLE
css issue occured theme color change while deleting

### ISSUE THREAD

**Issue by ajayvavdiya** [zignd/HTML-CSS-Class-Completion#360]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by eoussama** [comment]
This needs more elaboration

**Comment by ajayvavdiya** [comment]
NO NOW ISSUE RESOLVED.

**Comment by ajayvavdiya** [comment]
YOU CAN CLOSE THE ISSUE.

**Comment by eoussama** [comment]
I can't for I'm not the author of the issue.
