### ISSUE TITLE
Support for typescript (angular 2 templates)

### ISSUE THREAD

**Issue by jaroslawziolkowski** [zignd/HTML-CSS-Class-Completion#38]

**Comment by Aaltuj** [comment]
I would like to see this working in combination with angular2-inline extension. It wasn't clear to me when the css parser is triggerd. Is it only on html files?

**Comment by Zignd** [comment]
@Aaltuj sorry for this late response. Yeah, currently it only works on HTML files.

**Comment by zignd** [comment]
Closing this issue as the latest version now has support for TypeScript.
