### ISSUE TITLE
Indent in animated gif

### ISSUE THREAD

**Issue by alan-agius4** [Zignd/HTML-CSS-Class-Completion#41]
I know its not an issue but I absolute love the hrml formatting your have in the gif animations? What's the name of the fornatter?

Thanks

**Comment by Zignd** [comment]
Sorry, but what do you mean by "indent in animated gif"? I didn't understand what you said there.

**Comment by alan-agius4** [comment]
In the vs code demo that you are showing on the github homepage. You seem
that you are using some kind of HTML Formatter (ie to format your html) and
not the standard html formatter of vs code.

My question is what hrml formatter are you using.

Thanks

**Comment by Zignd** [comment]
Oh, I see what you mean now. I wasn't using a formatter, that attributes were indented manually. xD

**Comment by alan-agius4** [comment]
Ah thanks anyways :)
