### ISSUE TITLE
liquid support

### ISSUE THREAD

**Issue by onderakbulut** [zignd/HTML-CSS-Class-Completion#413]
Hi,
how can ı use this with panoply liquid extension and liquid files together

**Comment by panoply** [comment]
Hey @onderakbulut

Yeah, you can leverage this with my extension. Add the following to your workspace settings:

```json
{
  "html-css-class-completion.HTMLLanguages": [
    "liquid"
   ]
}
```

**Comment by onderakbulut** [comment]
it works perfectly thanks
