### ISSUE TITLE
Exclude node_modules

### ISSUE THREAD

**Issue by tfiwm** [Zignd/HTML-CSS-Class-Completion#46]
The plugin shows me everytime 99+ problems from node_modules files. In the fetcher you are excluding it. it seams that this works not well. I want to track them because if i use bootstrap e.g. this should work too but i don't want to get 99+ of warnings.

![image](https://cloud.githubusercontent.com/assets/988473/25220002/0d3ed17a-25b9-11e7-9245-98b2cd31f30a.png)

**Comment by Zignd** [comment]
Sorry, but the warnings you see weren't generated by this extension. Mainly because it doesn't generate warnings and error messages.
