### ISSUE TITLE
Define files to be cached

### ISSUE THREAD

**Issue by marcosvrs** [zignd/HTML-CSS-Class-Completion#47]
Have any configuration file that I can create to define which files/folders I want to cache?
For example:
I have so many css files in node_modules, but I want only the bootstrap.css file to be cached.
How can I define that?

**Comment by Zignd** [comment]
Whitelist and blacklist of folders and files is a feature we still have to implement, and it's already on the extension backlog. Unfortunately, I don't have free time right now to work on it.

**Comment by lemontreelxs** [comment]
我也很想要这个功能，看来还要等一等了。┭┮﹏┭┮

**Comment by zignd** [comment]
The recently released version adds a feature that is supposed to solve this issue.
