### ISSUE TITLE
Freezes VS Code

### ISSUE THREAD

**Issue by jensengar** [zignd/HTML-CSS-Class-Completion#52]
Not sure what information I can provide, but I thought I'd just report it. This addon freeze vs code for me. I verified this by disabling the extension. This happens every time in at least one of my projects. I have other projects that freeze occasionally but given that nature, there's no way for me to verify this extension is the cause of those. Happy to provide more information if directed.

**Comment by zignd** [comment]
I'm aware of this problem, it was reported some time ago, and the solution is to create a [language server](https://code.visualstudio.com/docs/extensions/example-language-server). It's quite hard to reproduce, and it seems to occur when you have a workspace with lots of CSS files. I'm working on it on my free time, but I can't give you a due date. Thanks for taking your time to report it. :)

**Comment by cgatian** [comment]
@zignd I dont know if this is related, but my VSCode no longer provides intellisense.  Disabling the extension fixes, and enabling breaks.

**Comment by zignd** [comment]
@cgatian It is. When the extension takes too long to cache the classes, it compromises the VS Code as a whole. I will work on a language server tonight so that we can have this workload in a separate process.

**Comment by cgatian** [comment]
Can you provide an update to at least prevent the behavior? I maintain an extension package that this uses, and don't want others to run into the bug.

**Comment by bardiainjast** [comment]
I have the same issue on my large projects, vscode freezes when the extension is caching classes

**Comment by zignd** [comment]
I guess this issue has been fixed in the latest update. All thanks goes to Erich Gamma for this great pull request https://github.com/zignd/HTML-CSS-Class-Completion/pull/90.
