### ISSUE TITLE
Extention not working (no autocompletions / Intellisense suggestions)

### ISSUE THREAD

**Issue by igpeev** [zignd/HTML-CSS-Class-Completion#53]
Typical Angular2 CLI setup, with Bootstrap CSS added via npm, CSS works when tested in code and project compiled, e.g.:
<div class="container-fluid"> ... </div>

The lightning pressed and shows updated status, but NO autocompletions / Intellisence suggestions 

Please advise

**Comment by zignd** [comment]
Hi @igpeev, just updated the extension to fix this issue. It seems that I committed a change that was causing the node_modules folder to be ignored, therefore causing problems like yours. Sorry for the inconvenience, just click the Update button on your Extensions tab to get the correction.

**Comment by igpeev** [comment]
Igor,
Great thanks for the prompt reaction.
Will check tm and re.

**Comment by zignd** [comment]
Np 👍

**Comment by igpeev** [comment]
Igor,
As promsed - tested, working as expected.

10x once again.

Cheers! :)
