### ISSUE TITLE
How can I use this plugin in other file mode

### ISSUE THREAD

**Issue by 404NoFound** [zignd/HTML-CSS-Class-Completion#6]
Hi, 
 now，I find this plugin only can use in *.html language mode.
 what can I do ,if I want use it in Razor Language Mode
 i

**Comment by Zignd** [comment]
That's quiet an interesting scenario to make use of it. Currently it's not possible, but I'm planning to rewrite the plugin in TypeScript on this next weekend and I will add this feature based on your request

**Comment by 404NoFound** [comment]
thx

**Comment by TheColorRed** [comment]
That would be nice! I use PHP files, and it doesn't work on those files.

**Comment by Zignd** [comment]
@TheColorRed PHP will be added as a supported file format too :smiley:

**Comment by ruudfortuin** [comment]
I'm using *.twig templates and would like to use this plugin also. Is it possible to add a configuration file which lists the filetypes in which the plugin can be used?

**Comment by Zignd** [comment]
That's a good idea @ruudfortuin, I will look into that. Would certainly be better than adding support for specific file types.

**Comment by ruudfortuin** [comment]
Great, I'm looking forward to using your plugin in my Twig templates :-)

**Comment by BeelzeBu** [comment]
+1 This is my most wanted feature from Visual Studio, go for it :) if you need help to test let me know.

**Comment by BeelzeBu** [comment]
@Zignd Any updates, this is a must have. please don't forget us 👍

**Comment by Zignd** [comment]
@BeelzeBu I have not forgotten you guys, and sorry for taking so long to release this update, but it's real life at work that is fucking up with my routine, but this weekend I will have some time to work on it, I just ask you guys some patience.

**Comment by BeelzeBu** [comment]
@Zignd Any updates, this is a must have. please don't forget us 👍, I know you could be busy but I think this is a marvelous extension

**Comment by zignd** [comment]
Closing this issue as the latest version now has support for Razor, PHP and Twig.
