### ISSUE TITLE
Ignore or define folders

### ISSUE THREAD

**Issue by dradickLRE** [zignd/HTML-CSS-Class-Completion#62]
This is may just be a question, not an issue. (Couldn't find a twitter handle)

Is there a way to configure certain folders to ignore .css files in? 

Several of my projects have a template folder within the root that is just for reference. Any actual files being used are moved into a proper public folder. I suppose defining one or multiple folders could be an option as well. This may help speed up the drag on VSCode the extension has when building the cache.

**Comment by eko3alpha** [comment]
I'm having this issue as well.  I've not found a way to prevent it from scanning my node_modules and vendor directories.

**Comment by manuelswd** [comment]
Same here... implement a method to ignore certain folder would be really appreciated.

**Comment by sabinrimni** [comment]
I would like this feature for another reason. My "Problems" view is cluttered with css issues from the "node_modules" folder and I would like to exclude it from the linting.

![capture](https://user-images.githubusercontent.com/6349949/28967447-75f39ce0-791b-11e7-9771-e0bf473ac43b.PNG)

**Comment by nealoke** [comment]
I've just discoverd it also covers all my node_modules which is totally unnecessary for my project. Any way I could help @zignd ?

![extension host](https://user-images.githubusercontent.com/17417414/29451582-776b9120-8403-11e7-85d2-a38475dda429.PNG)

**Comment by nealoke** [comment]
@zignd I'll look if I have time, any pointers on first contributing to a vscode extension? :)

**Comment by zignd** [comment]
@nealoke Let me see:
* Clone the repo
* Install Yarn
* `yarn install` for the dependencies
* `code .` in the repository directory
* Make your changes
* F5 to run the extension in Debug mode
* New window opens up with an isolated VS Code instance running and the extension will be already installed in it
* You can set break points in the VS Code containing the extension code (not the one running the extension installed)

In case you have any other doubts feel free to contact me, there's some contact info in my profile bio.

**Comment by zignd** [comment]
@nealoke I forgot to mention, documentation related to how VS Code extensions work can be found here: [Extensibility Reference](https://code.visualstudio.com/docs/extensionAPI/overview). And here is the documentation for the classes, methods, functions and everything code-related: [vscode namespace API](https://code.visualstudio.com/docs/extensionAPI/vscode-api). Very useful resources.

**Comment by PixelT** [comment]
+1 for this "issue"
Now it's cache all CSS in `node_modules` which isn't a good idea :)

**Comment by zignd** [comment]
The recently released version adds a feature that is supposed to solve this issue.
