### ISSUE TITLE
Causes all files in node_modules to be linted

### ISSUE THREAD

**Issue by teamsteamdev** [zignd/HTML-CSS-Class-Completion#64]
Recently I've noticed that I'm getting a lot of items under the Problems tab in VS Code. All of the files are in `node_modules`. 

Disabling all extensions eliminates these items, and enabling "IntelliSense for CSS class names" causes the items to reappear. Enabling all extensions except "IntelliSense for CSS" once again eliminates these items.

Is this the intended behavior?

**Comment by stephen-nba** [comment]
I found the same thing. Is this extension supposed to lint all my CSS as well? Even in the node_modules folder?

**Comment by marcelo-mason** [comment]
An option to exclude paths from showing problems would be nice.  I may want intellisense from vendor folders, but I don't care about the problems it has.

**Comment by imaia** [comment]
My VS code freezes and crashes with this extension. I'm quite sure this issue problem is related to it. I starts looking for css classes and crashes.

**Comment by gobijan** [comment]
VS Code also freezes caused by this extension

**Comment by bgarrant** [comment]
I am having the same issue.  How can we exclude folders?

**Comment by bgarrant** [comment]
try this extension for a quick fix if needed while this is being worked on: https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css

**Comment by phifa** [comment]
@bgarrant i dont get it, how does the extension help exactly? just trying to understand.

**Comment by bgarrant** [comment]
That extension does not have the issue with the node_modules folder.  Probably not as full featured but it seems to work OK in my tests.

**Comment by Chanran** [comment]
my vs code crash too! all node_modules css files lint and cause 99 warns and 99 errors.

**Comment by mcleanra** [comment]
+1

**Comment by bastian-w** [comment]
i just excluded `node_modules` completely. 
```
files.exclude: {
        "**/.git": true,         
        "**/.DS_Store": true, 
        "**/node_modules": true
}
```

**Comment by ikzjfr0** [comment]
+1, i have the same thing here.

**Comment by reflog** [comment]
same here. bummer

**Comment by fgeierst** [comment]
The following prevents `node_modules` folders to get linted:

**User settings**
```
"files.exclude": {
        "**/.git": true,         
        "**/.DS_Store": true, 
        "**/node_modules": true
}
```

This said, I still think the extention should ignore  `node_modules` folders by default.

**Comment by Luca-Terrazzan** [comment]
Excluding the node_modules also prevents it from showing up in vscode entirely...what if I want to browse it from time to time? An option to exclude path from the plugin is necessary imho

**Comment by rkpatel33** [comment]
+1

For me the `files.exclude` option is not ideal. A package specific setting would be better I think.

**Comment by zignd** [comment]
The recently released version adds a feature that is supposed to solve this issue.

**Comment by bardware** [comment]
> The following prevents node_modules folders to get linted

I hoped for that but I'm not sure it works. My project is very small, the `node_modules` folder, however, is large. VSCode takes it's time to start up because of this plugin.
