### ISSUE TITLE
Windows: Extension host terminated unexpectedly. Please reload the window to recover

### ISSUE THREAD

**Issue by dharders** [zignd/HTML-CSS-Class-Completion#65]
After upgrading vscode to 1.13.1 on Windows 10 I started experiencing the error:

> Extension host terminated unexpectedly. Please reload the window to recover

This appears every time after 2-3 minutes of use after the window reloads. All extensions stop working after this.

I'm not sure if the vscode update caused it or your extension v1.7.0 but it is now unusable on Windows 10 (medium size project).

The only way I have made the issue disappear so I can use vscode is by disabling your extension.

Related #57 (Same Crash but Ubuntu), #58, #35

**Comment by marcelo-mason** [comment]
Same here.

**Comment by zignd** [comment]
I guess this issue has been fixed in the latest update. Thanks to Erich Gamma for this great pull request #90.
