### ISSUE TITLE
breaks jump to definition and tooltips when used with `polymer-ide` extension

### ISSUE THREAD

**Issue by hariprasadiit** [zignd/HTML-CSS-Class-Completion#67]
### steps to reproduce:

1. install above mentioned extension
2. use polymer-starter-kit-2 and try jump to definition

**Comment by zignd** [comment]
I need more information to reproduce the bug as I'm not versed in Polymer, and a link to the extension mentioned above would be quite handy as there lots of similar ones in the Marketplace.
