### ISSUE TITLE
Options to hide fetching css rules notification

### ISSUE THREAD

**Issue by autoferrit** [Zignd/HTML-CSS-Class-Completion#7]
Currently, any time i open any file with css in it, I get this notification

![image](https://cloud.githubusercontent.com/assets/89895/14211801/d570802a-f7e4-11e5-90ed-b73239c8b065.png)

And they never go way until I explicitly close them. I realize this may be an issue with vs code core, but I was hoping that since its so common to go between files with css rules, that there be an option in the settings to not show this notification. Or somehow hide it after a few seconds.

**Comment by Zignd** [comment]
Those notifications are annoying and intrusive, but I will replace them with status bar notifications on the next version of the plugin, but I'd like to ask you to wait until the end of this weekend, I'm currently working on a complete rewrite of the plugin in TypeScript and by Monday or Sunday I will release a new version.

**Comment by SkiftCreative** [comment]
No worries. Thanks for the update.

**Comment by rbatukaev** [comment]
Any updates?

**Comment by martonx** [comment]
Please update the plugin, those notifications are very annoying.

**Comment by Zignd** [comment]
Annoying notifications removed on the latest version. Thank you guys for the feedback!
