### ISSUE TITLE
don't work on .vue file

### ISSUE THREAD

**Issue by thearabbit** [zignd/HTML-CSS-Class-Completion#70]
don't work on .vue file
```js
<template>
    <div class="layo...">
</template>

<style scoped>
.layout {
    border: 0px solid #d7dde4;
    background: #f5f7f9;
}
```

**Comment by zignd** [comment]
Do you have [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) installed? It is required because it adds language support for Vue.
