### ISSUE TITLE
Autocomplete of CSS in Project files doesn't work

### ISSUE THREAD

**Issue by cwcoffman** [zignd/HTML-CSS-Class-Completion#72]
I have bootstrap classes loaded in node_modules and they show up when using Ctrl+Space.  Nothing otherwise.  If I type a 'space' first, autocomplete starts, but not if I don't.  This makes it about the same as hitting Ctrl+Space first.  

The following are all extensions I have installed:

abusaidm.html-snippets
alexiv.vscode-angular2-files
DavidAnson.vscode-markdownlint
donjayamanne.python
eg2.tslint
groksrc.ruby
guosong.bracketselection
hubertstrk.pgsql-html
infinity1207.angular2-switcher
jakethashi.vscode-angular2-emmet
Mikael.Angular-BeastCode
ms-vscode.PowerShell
ms-vscode.Theme-MarkdownKit
msjsdiag.debugger-for-chrome
natewallace.angular2-inline
PeterJausovec.vscode-docker
pmneo.tsimporter
rebornix.Ruby
Shan.code-settings-sync
steoates.autoimport
thekalinga.bootstrap4-vscode
xabikos.JavaScriptSnippets
Zignd.html-css-class-completion

Thoughts?

**Comment by zignd** [comment]
Correct me if I didn't understand your question. But isn't that the expected behavior? Whenever you press Ctrl+Space or just type a quotation mark, the available options appear.

**Comment by cwcoffman** [comment]
Yes, sorry for not being clear.  That is the expected behavior, of course.
I was, however, *also* hoping to find a way to have it auto-complete as I'm
typing!  Let me know if I'm barking up the wrong tree.

Thanks!

**Comment by zignd** [comment]
I believe you can do that already. As soon as you write something like `class="` the IntelliSense window will open, and suggestions based on what you type after that will be filtered in this window by every letter you type. Then you can press Tab or choose another option by browsing through the available options with the up and down arrow keys followed by a Tab or Enter keypress. This IntelliSense window behavior is something built-in, and the extension developer can't do much about it, but provide the items to display in the list or provide additional documentation for each item.

**Comment by zignd** [comment]
Maybe I failed to understand you again, but correct me again if I'm wrong. xD

**Comment by cwcoffman** [comment]
For whatever reason, my version (latest) doesn't do this as I type.  Maybe
it's a setting I need to change.

Good to know it can do that - just need to figure out how to make it happen!

Thank you.
