### ISSUE TITLE
Don't work in HTML files

### ISSUE THREAD

**Issue by hellofedorov** [zignd/HTML-CSS-Class-Completion#75]
Hello! I have such an HTML file:
![2017-08-23 17 15 52](https://user-images.githubusercontent.com/9901120/29620508-cb263ad2-8826-11e7-875e-86a38df7e780.png)

and CSS file:
![2017-08-23 17 17 02](https://user-images.githubusercontent.com/9901120/29620550-e5c119de-8826-11e7-8601-3a9a08902e34.png)

When I try to add class to div nothing happens. Why can I fix such behavior of extension?
![vscode_](https://user-images.githubusercontent.com/9901120/29620796-9a138f02-8827-11e7-95bd-6d343d0f8f9c.gif)

_MacOS 10.11, VSC 10.15.1, IntelliSense 1.8.1_

**Comment by hellofedorov** [comment]
Sorry, but I found a solution.
It turns out that extension searches for CSS files in your project folder and all subfolders and don;t searches if I haven't project folder. 

I think it's worth adding this clarification to the FAQ

**Comment by zignd** [comment]
No problem. 

Yup, you need a workspace. xD

Actually, there's some information about it in the "Usage" section. I might add a troubleshoot section next time.
