### ISSUE TITLE
CSS file containing a parsing error break extension

### ISSUE THREAD

**Issue by Angelinsky7** [Zignd/HTML-CSS-Class-Completion#8]
if one css file contains a parsing error the hole process crash.
An error handling method would be better...

**Comment by joelfmrodrigues** [comment]
I had the same problem and changed the code to parse one file at a time as some of the css files causing errors belong to external packages. That solved the problem for me! Submitted a PR, but no response :(

**Comment by Zignd** [comment]
Fixed on the latest release. Thanks for the report!
