### ISSUE TITLE
blade.php is not supported

### ISSUE THREAD

**Issue by saidbakr** [zignd/HTML-CSS-Class-Completion#83]
In Laravel projects `blade.php` files is not supported. i.e there is no autocomplete list of CSS classes.
Version: 1.9.0, VScode 1.15.1, Ubuntu Linux 16.04, Laravel 5.4 Project.

**Comment by zignd** [comment]
Just tried it on a PHP file and it worked. How does this `blade.php` file differs from regular PHP files? Sorry, but I'm not versed in PHP.

**Comment by WaqasIbrahim** [comment]
There is no single file named `blade.php` in Laravel. The templating engine used for Laravel views is Blade so all Blade view files use the `.blade.php` file extension.

@saidbakr Are you using SCSS to generate CSS?

**Comment by DanJFletcher** [comment]
I have the same problem. The extension can pick up all of my CSS classes in any `.php` or `.html` file but it won't work inside of blade templates. I'm also using SCSS btw.

**Comment by lamberttraccard** [comment]
Same for me.
