### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Esteban-Rocha** [zignd/HTML-CSS-Class-Completion#91]
Issue on:

Version 1.17.1
Commit 1e9d365
Date 2017-10-10T14:21:18.489Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

System:
Arch linux, 64x
iCore7 - 16GB RAM

After activating this extension CPU increases 40% to 50%, RAM also suffers a 500MB to 1GB increase.

I'm a WP Dev I do not use npm a lot, In many projects it doesn't even exist, still I get this result, so you may want to have that into consideration about the node_modules directory because it should something else that's adding into the mix of CPU leaking, maybe a option to scope which directories to index or to exclude on indexing for the caching may help? just and idea but I think it may help as it seems to be an issue that triggers on projects with a lot of files and folders.

Thx!

**Comment by pungggi** [comment]
A good idea to borrow is here> https://stackoverflow.com/questions/38063144/can-you-pass-multiple-glob-strings-to-vscode-findfiles-api

Basically exclude files that you do not want in your search should suffice..

**Comment by zignd** [comment]
The recently released version adds a feature that is supposed to solve this issue.
