### ISSUE TITLE
Get error and danger of the whole project

### ISSUE THREAD

**Issue by Tekbr** [zignd/HTML-CSS-Class-Completion#92]
- VSCode Version: 1.18.0 - Insiders
 - OS Version: Windows 10

Obter erro e perigos de todo o projeto

Olá.

Em versões anteriores de sua extensão clicar em "CSS classes cache" ou abri o VSCode pela primeira vez ou usar a opção de recarregar janela, o mesmo e mostrava erro e perigos em todo o mesmo projeto.
Porém na sua versão mais nova está me limitando a somente no arquivo que estou aberto, como funciona o VSCode sem sua extensão.

Sei que o objetivo da extensão não é esse, mas é uma função interessante.

Alguma forma de obter esse recurso novamente, ao clicar em "CSS classes cache"?

--------------------------------------------------------------------------------------------------------------

-- Sorry for the English, I used Google Translator --

Hello

In previous versions of your extension click on "CSS classes cache" or open the VSCode for the first time or use the option to reload window, it would display error and dangers throughout the same project.
But in its newer version it is limiting me to only the file that I am open, how the VSCode works without its extension.

I know the purpose of extension is not this, but it's an interesting function.

Any way to get this feature again, when I click on "CSS classes cache"?

**Comment by zignd** [comment]
Olá @Tekbr, muitas pessoas me pediram para remover essa validação, ela ocorria por causa da maneira como a extensão estava obtendo o conteúdo dos arquivos que ela considera para encontrar as definições de classes, engraçado, você é a primeira pessoa que me pede o contrário xD.

Então, essa funcionalidade que você deseja é possível através de um tipo de ferramenta chamada linter, ele faz esse trabalho de analisar o código e retornar avisos e erros. Existe um opção de linter para CSS, SCSS e Less no marketplace que parece ser confiável e que você pode testar, veja: https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint

**Comment by Tekbr** [comment]
@zignd Tentei a extensão que falou. Ela não funcionou da mesma forma que funcionava a sua ou eu não configurei corretamente. 😆 😊 

A sua funcionava de maneira automática. 😄 Por sinal, nunca tive problema com ela... usando desde o início quando comecei a usar o VSCode.

Alguma chance de voltar com essa funcionalidade?
Alguma opção que venha por padrão desativada,  e ao ativar, ter essa funcionalidade novamente?

Desde já agradeço a atenção.

**Comment by zignd** [comment]
Desculpa ter demorado tanto para te responder @Tekbr, eu realmente não vi a notificação referente a essa mensagem. Então, essa "funcionalidade" gerou muitas issues nesse repositório e no repositório do VS Code, porque era um comportamento que realmente não fazia sentido em conjunto com essa extensão, então para evitar futuras confusões com esse comportamento prefiro manter como está. Espero que você entenda e desculpa qualquer coisa.

Ah sobre o linter, existem outras alternativas e você pode tentar abrir issues nesses projetos para requisitar suporte na configuração. Eu particularmente, não uso porque meu dia-a-dia é mais focado em back-end.

**Comment by Tekbr** [comment]
> porque era um comportamento que realmente não fazia sentido em conjunto com essa extensão

@zignd Discordo um pouco.

Mas como sugeri, uma nova função que venha desativada por padrão, funcionando da forma atual. E quando ativada, a mesma funciona de maneira que faça o do erro.

Ainda acho válido o pedido de volta do recurso. 😉 Uma vez que mesmo funciona de forma correta.
