### ISSUE TITLE
Add support for CSS definitions from JavaScript files in the zeit/styled-jsx format

### ISSUE THREAD

**Issue by pungggi** [zignd/HTML-CSS-Class-Completion#98]
Hi for people using css in js solutions would be great to have this too..

It should be possible extracting the css from literals?

Similar to https://github.com/zignd/HTML-CSS-Class-Completion/issues/69
But should be easier to accomplish.

**Comment by zignd** [comment]
It is possible to extract, but it's tricky to differentiate a JavaScript object literal used for a specific purpose in the application of an object literal containing CSS definitions. But I'm open to ideas on how to interpret the code in this use case.

**Comment by pungggi** [comment]
Yes thats true but most of the time it just find startTag  endTag of a
specfic function..

Example startTag: cssʼ
endTag: ʼ

If these were configurable, it would be flexible enough..

Am 13.11.2017 12:22 nachm. schrieb "Igor H. Vieira" <
notifications@github.com>:

It is possible to extract, but it's tricky to differentiate a JavaScript
object literal used for a specific purpose in the application of an object
literal containing CSS definitions. But I'm open to ideas on how to
interpret the code in this use case.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zignd/HTML-CSS-Class-Completion/issues/98#issuecomment-343890191>,
or mute the thread

**Comment by zignd** [comment]
Are you talking about the same thing? At first, I thought you were suggesting a parsing engine for JS, one that would traverse the JavaScript files in a workspace looking for CSS class definitions inside object literals. But now it seems that you're talking about auto completion inside JavaScript files.

**Comment by pungggi** [comment]
I really mean traverse js and or jsx to find css classes..

**Comment by pungggi** [comment]
Shouldn t autocomplete already work with react?

**Comment by pungggi** [comment]
I tried hacking a little bit with this extension, and what I see right now is that, when including javascript files the caching process takes some time.
It should be possible to include or exclude certain pathes to search for. (maybe with regex?)

**Comment by zignd** [comment]
> I really mean traverse js and or jsx to find css classes..
> See for example https://github.com/zeit/styled-jsx/blob/master/readme.md#keeping-css-in-separate-files

Oh, so you're suggesting support for CSS definitions in the format defined by the `styled-jsx` project you recently linked up there? Their format is possible to parse and there will be no conflicts with object literals.

> Shouldn t autocomplete already work with react?

It already works, but you shows you auto completions only, it doesn't parse React code looking for CSS definitions.

**Comment by pungggi** [comment]
yes this would be a good step..

**Comment by pungggi** [comment]
@zignd Can I suggest a PR for this?

**Comment by zignd** [comment]
Sure, I'd gladly review. Are you planning to work on those two formats?

```
<style jsx>{`
      p {
        color: red;
      }
    `}</style>
```
```
export default css`div { color: green; }`
```

**Comment by pungggi** [comment]
Yes both.
